services:
  lhwdev-mc-railway:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25564:25565"

    environment:
      TYPE: NEOFORGE
      VERSION: 1.21.1
      NEOFORGE_VERSION: 21.1.109
      EULA: true

      MEMORY: 10g
      USE_AIKAR_FLAGS: true

      MOTD: "§cS§aC§9G§f 공?식 모딩 서버§r by §6이현우"

    volumes:
      - /home/scg/lhwdev/mc-railway-server/data:/data
